import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { HomeWrapper, HeadlineWrapper } from "../styles/HomeStyles";

export default function Home() {
  return (
    <HomeWrapper>
      <Head>
        <title>Alex Broussard Pottery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeadlineWrapper>
          <aside>
            <img
              src={
                "https://res.cloudinary.com/abpottery/image/upload/v1655991687/5431D0F6-EECC-4928-95E0-86731BB9C5DA_hldply.png"
              }
            />
          </aside>
          <article>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem
              dolor sed viverra ipsum. Faucibus purus in massa tempor nec. Netus
              et malesuada fames ac turpis egestas integer eget. Luctus
              venenatis lectus magna fringilla. Cursus in hac habitasse platea.
              Euismod in pellentesque massa placerat duis ultricies lacus.
              Imperdiet massa tincidunt nunc pulvinar sapien et ligula. Quis
              imperdiet massa tincidunt nunc pulvinar. Amet massa vitae tortor
              condimentum lacinia. Commodo ullamcorper a lacus vestibulum sed
              arcu. Tellus mauris a diam maecenas sed enim. Tellus id interdum
              velit laoreet id. Lorem ipsum dolor sit amet consectetur
              adipiscing elit ut aliquam. Sem integer vitae justo eget. Dolor
              sit amet consectetur adipiscing elit pellentesque habitant morbi
              tristique. Dictumst vestibulum rhoncus est pellentesque.
            </p>
          </article>
        </HeadlineWrapper>
      </main>
    </HomeWrapper>
  );
}
